# Generated by Django 5.2 on 2025-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
