# Generated by Django 5.2 on 2025-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialwallpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='socialwallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/'),
        ),
    ]
