# Generated by Django 5.2 on 2025-05-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('mens_clothing', 'Men’s Clothing'), ('womens_clothing', 'Women’s Clothing'), ('childs_clothing', 'Child’s Clothing'), ('mens_shoes', 'Men’s Shoes'), ('womens_shoes', 'Women’s Shoes'), ('childs_shoes', 'Child’s Shoes'), ('mens_accessories', 'Men’s Accessories'), ('womens_accessories', 'Women’s Accessories')], default='Uncategorized', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default=1, help_text='Comma-separated tags', max_length=200),
            preserve_default=False,
        ),
    ]
