# Generated by Django 5.2 on 2025-05-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image_url_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
