<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-29 07:51
=======
# Generated by Django 5.2 on 2025-04-26 18:57
>>>>>>> 5df4f2df0734fccee54bb6b324586aa9d0d8b5cc

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
