# Generated by Django 5.2 on 2025-05-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image_url',
            new_name='profile_image',
        ),
    ]
